services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.prd  # Carrega as variáveis de ambiente a partir do arquivo .env.prd
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: apei_database_prd
      POSTGRES_USER: apei_user
      POSTGRES_PASSWORD: escolainclusao
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: