name: Deploy APEI

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/apei-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USER }}/apei-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to AWS EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: 22

      - name: Copy docker-compose.yml and .env to EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          source: |
            docker-compose.yml
            .env.prd
          target: ec2-user@${{ secrets.AWS_EC2_HOST }}:/home/ec2-user/
          key: ${{ secrets.AWS_EC2_SSH_KEY }}

      - name: Pull Docker Image on EC2 and Run Containers
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            docker-compose pull
            docker-compose up -d
